// <auto-generated />
using System;
using CoreWhatIf.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace corewhatif.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529113443_AddSavedSimulationsAndPlans")]
    partial class AddSavedSimulationsAndPlans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreWhatIf.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .HasColumnType("text")
                        .HasColumnName("activity");

                    b.Property<decimal>("ArrActual")
                        .HasColumnType("numeric")
                        .HasColumnName("arr_actual");

                    b.Property<decimal>("ArrCore")
                        .HasColumnType("numeric")
                        .HasColumnName("arr_core");

                    b.Property<string>("BusinessName")
                        .HasColumnType("text")
                        .HasColumnName("business_name");

                    b.Property<string>("Cif")
                        .HasColumnType("text")
                        .HasColumnName("cif");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<int>("ClientCode")
                        .HasColumnType("integer")
                        .HasColumnName("client_code");

                    b.Property<decimal>("DamRate")
                        .HasColumnType("numeric")
                        .HasColumnName("dam_rate");

                    b.Property<decimal>("DeltaArr")
                        .HasColumnType("numeric")
                        .HasColumnName("delta_arr");

                    b.Property<string>("Erp")
                        .HasColumnType("text")
                        .HasColumnName("erp");

                    b.Property<bool>("HasAuna")
                        .HasColumnType("boolean")
                        .HasColumnName("has_auna");

                    b.Property<bool>("HasFegime")
                        .HasColumnType("boolean")
                        .HasColumnName("has_fegime");

                    b.Property<bool>("HasMobileA")
                        .HasColumnType("boolean")
                        .HasColumnName("has_mobile_a");

                    b.Property<bool>("HasMobileE")
                        .HasColumnType("boolean")
                        .HasColumnName("has_mobile_e");

                    b.Property<bool>("HasObras")
                        .HasColumnType("boolean")
                        .HasColumnName("has_obras");

                    b.Property<decimal>("InfraCost")
                        .HasColumnType("numeric")
                        .HasColumnName("infra_cost");

                    b.Property<bool>("IsDam")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dam");

                    b.Property<decimal>("MonthlyRate")
                        .HasColumnType("numeric")
                        .HasColumnName("monthly_rate");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Partner")
                        .HasColumnType("text")
                        .HasColumnName("partner");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<int>("UsersErp")
                        .HasColumnType("integer")
                        .HasColumnName("users_erp");

                    b.HasKey("Id");

                    b.HasIndex("ClientCode")
                        .IsUnique();

                    b.HasIndex("IsDam");

                    b.HasIndex("Partner");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("CoreWhatIf.Models.CloudClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ArrCloud")
                        .HasColumnType("numeric")
                        .HasColumnName("arr_cloud");

                    b.Property<int>("ClientCode")
                        .HasColumnType("integer")
                        .HasColumnName("client_code");

                    b.HasKey("Id");

                    b.HasIndex("ClientCode")
                        .IsUnique();

                    b.ToTable("cloud_clients");
                });

            modelBuilder.Entity("CoreWhatIf.Models.DummyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DummyRecords");
                });

            modelBuilder.Entity("CoreWhatIf.Models.MrrHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Apr26")
                        .HasColumnType("numeric")
                        .HasColumnName("apr_26");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<decimal>("Feb26")
                        .HasColumnType("numeric")
                        .HasColumnName("feb_26");

                    b.Property<decimal>("Jan26")
                        .HasColumnType("numeric")
                        .HasColumnName("jan_26");

                    b.Property<decimal>("Mar26")
                        .HasColumnType("numeric")
                        .HasColumnName("mar_26");

                    b.HasKey("Id");

                    b.ToTable("mrr_history");
                });

            modelBuilder.Entity("CoreWhatIf.Models.RoadmapFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EffortWeeks")
                        .HasColumnType("integer")
                        .HasColumnName("effort_weeks");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feature_name");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ready");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("PlannedDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_date");

                    b.Property<string>("PlannedVersion")
                        .HasColumnType("text")
                        .HasColumnName("planned_version");

                    b.Property<string>("SatelliteProduct")
                        .HasColumnType("text")
                        .HasColumnName("satellite_product");

                    b.HasKey("Id");

                    b.ToTable("roadmap_features");
                });

            modelBuilder.Entity("CoreWhatIf.Models.SatelliteProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientCode")
                        .HasColumnType("integer")
                        .HasColumnName("client_code");

                    b.Property<DateOnly?>("ContractDate")
                        .HasColumnType("date")
                        .HasColumnName("contract_date");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocked");

                    b.Property<string>("Partner")
                        .HasColumnType("text")
                        .HasColumnName("partner");

                    b.Property<int>("PartnerCode")
                        .HasColumnType("integer")
                        .HasColumnName("partner_code");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductVariant")
                        .HasColumnType("text")
                        .HasColumnName("product_variant");

                    b.Property<int>("Province")
                        .HasColumnType("integer")
                        .HasColumnName("province");

                    b.Property<int>("UsersProduct")
                        .HasColumnType("integer")
                        .HasColumnName("users_product");

                    b.HasKey("Id");

                    b.HasIndex("ClientCode");

                    b.HasIndex("ProductName");

                    b.ToTable("satellite_products");
                });

            modelBuilder.Entity("CoreWhatIf.Models.SavedPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail");

                    b.ToTable("SavedPlans");
                });

            modelBuilder.Entity("CoreWhatIf.Models.SavedSimulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail");

                    b.ToTable("SavedSimulations");
                });

            modelBuilder.Entity("CoreWhatIf.Models.CloudClient", b =>
                {
                    b.HasOne("CoreWhatIf.Models.Client", "Client")
                        .WithOne("CloudClient")
                        .HasForeignKey("CoreWhatIf.Models.CloudClient", "ClientCode")
                        .HasPrincipalKey("CoreWhatIf.Models.Client", "ClientCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CoreWhatIf.Models.SatelliteProduct", b =>
                {
                    b.HasOne("CoreWhatIf.Models.Client", "Client")
                        .WithMany("SatelliteProducts")
                        .HasForeignKey("ClientCode")
                        .HasPrincipalKey("ClientCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CoreWhatIf.Models.Client", b =>
                {
                    b.Navigation("CloudClient");

                    b.Navigation("SatelliteProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
